### ISSUE TITLE
FMSY calcs not working for some models

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3models#12]
The `profile_fmsy` function is returning 0 for all values of F for 
mac-age-selex-om, mac-om, yel-om
and crashing for yelloweye_age_based_om

**Comment by peterkuriyama** [comment]
@Kotkot um help?

**Comment by peterkuriyama** [comment]
Just asked @taylori and he said that species like mackerel which don't really have a stock-recruit relationship have issues estimating Fmsy. There may not be problems with the rest of the model, just estimations of Fmsy.

**Comment by cstawitz** [comment]
That wouldn't explain yelloweye though..

On Tue, Feb 10, 2015 at 10:35 AM, Peter Kuriyama notifications@github.com
wrote:

> Just asked @taylori https://github.com/taylori and he said that species
> like mackerel which don't really have a stock-recruit relationship have
> issues estimating Fmsy. There may not be problems with the rest of the
> model, just estimations of Fmsy.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ss3sim/growth_models/issues/12#issuecomment-73755604.

## 

Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Comment by iantaylor-NOAA** [comment]
If yelloweye isn't working, that's mysterious.
Also, I was thinking of the internal MSY calculations in SS, not the ss3sim
function profile_fmsy.
I just looked at profile_fmsy and I don't see too many things that could go
wrong. It should also be relatively easy (for someone
more knowledgeable about ss3sim than me) to confirm that change_f is
working properly and then check that the data.ss_new files are being
produces and contain updated catch values.
-Ian

**Comment by Kotkot** [comment]
I think it is related to the r4ss function 'SS_readdat' that is used wthin the profile_fmsy function. 

It tries to get to the last year's catch from the fishery using the command:
SS_readdat("data.ss_new", verbose = FALSE,
                            section = 2)$catch$Fishery[simlength]

except that in the version of r4ss that I have, the name of the fishery is not "Fishery" but "fishery" + whatever fishery fleet number. Which gives in our case, "fishery1"
SS_readdat("data.ss_new", verbose = FALSE,
                            section = 2)$catch$fishery1[simlength]

I changed the profile_fmsy and pushed in on github and at least it works for some of the models where it failed for Cole.

**Comment by colemonnahan** [comment]
Hi Kot, I don't see this on github. Could you check that you pushed to master? Thanks!

**Comment by kellijohnson-NOAA** [comment]
Catch in the OM needs to be a value other than zero, even if it is just 1. If zero the F values from the par file will not be used to generate expected catches in the data.ss_new file. Fixed mac model with commit 3314914a49a9275dc80c09d59f185bd1a806cd5c

@Kotkot fixed the "Fishery" label issue in with ss3sim/ss3sim@2b4caaa5e98d34d4bd87f6d4758eddd2be7e962a

Still need to see if all models will run now.

**Comment by colemonnahan** [comment]
Ok so these are running for the new models but mackerel is REALLY high. See plot [here](https://github.com/ss3sim/ss3models/blob/master/catch_curves.png). This doesn't seem reasonable to me... does F have a different meaning for that model?

**Comment by kellijohnson-NOAA** [comment]
@colemonnahan can you  
- add `F.start.list` and `F.end.list` values for each species;
- use `F.start` in the call to `profile_fmsy`;

@seananderson do you have any workflow recommendations for scripts like these? It is not really a test, so I am unsure where the file should be stored. Should we implement `system.file()` calls to set the directories where the models would be found and where the plots should be sent?

**Comment by colemonnahan** [comment]
@kellijohnson Happy to make those changes, but was waiting to see which models were going to be dropped/renamed. I like the idea of having plots that illustrate the properties of the models, that's why I made a new plots folder. In fact I think we should add key biological plots as well. Do you object to a plots folder?

**Comment by seananderson** [comment]
I believe the revised folder setup with have a folder structure that looks like:

```
cod/README.md
cod/om/
cod/em/
```

I suggest we make the `README.md` file an RMarkdown file `README.Rmd`, have a `plots` folder for each species, and turn that readme into a little description of the model with some embeded output plots. That will render nicely on GitHub. This is very simple to setup and I'm happy to take R code and do it. You'll just run `rmarkdown::render()` on the `README.Rmd` to recreate the plots and Markdown file. I can set this up with Kelli when we rearrange the folders.
