### ISSUE TITLE
Adding dummy index data

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3models#17]
At some point the dummy index data from the input OM dat files was removed for fleet 2. I think we need to add this back so that we can use survey index data in the models. Is it best to do this manually for each model? An alternative is to modify `change_data` to do this automatically, and then the unused rows would be stripped out in `clean_data`... @seananderson or @Kotkot have any thoughts on best way forward with this?

**Comment by seananderson** [comment]
Ah right. That's probably why I was only checking for fleets 1 and 3 by default in `check_data`.

Not sure it matters which way we do it. I guess I'd favour whichever way is most transparent in the future. One one hand it seems weird to have `change_data` adding in data, but then it already does that for other data types. But it also seems weird if the OMs have dummy data for fleets 1 and 3 but not 2, which is added in later. So, maybe for now I favour adding the data directly into the OM .dat files... I'm happy to do that.

**Comment by colemonnahan** [comment]
@seananderson that would be great if you have time. I've moved on to other fires.

**Comment by Kotkot** [comment]
Wait, I don't know what you are talking about. 
For the abundance indices, all OM ."dat" have dummy index from year 1 to 100 for fleet 2 = survey and for fleet 3 = CPUE. 
Never for fleet 1. Fleet 3 is basically the same as fleet 1 but only specialized to abundance index. That is what we decided in the past.

Am I misunderstanding what you are talking about?

**Comment by seananderson** [comment]
You're correct Kot. I checked and indeed all the models have index data for fleets 2 and 3. Nothing to see here. Moving on...
