### ISSUE TITLE
Phases all negative in yellow EM

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3models#18]
Negative phases in the em.ctl file for yellow. Is this an issue with standardization functions? @cstawitz help!

**Comment by cstawitz** [comment]
I don't think so - it shouldn't be changing the phase?

**Comment by colemonnahan** [comment]
I thought your function wrote that nice table of phases/bounds/inits for the models? Can we turn that on and put the results in the extra folder for now?

**Comment by seananderson** [comment]
I moved that lovely function into the package. Just a sec and I'll write a
little script that outputs a table in Markdown that we can nicely read on
GitHub.

**Comment by cstawitz** [comment]
I think SS_parlines is the function you're thinking of Cole.

**Comment by kellijohnson-NOAA** [comment]
So what happened is there is an argument to `SS_changepars` called `estimate`, the default is `FALSE` which will turn all phase to negative values. When you call `standardize_bounds` you need to add `estimate = NULL`, then the phase will not be altered.

**Comment by kellijohnson-NOAA** [comment]
Fixed with c7973a8da249cd18bf6f930f5e48d162a356dfc9, phases are now as they were.

**Comment by cstawitz** [comment]
I added estimate = NULL as an argument to SS_changepars within
standardize_bounds so this won't happen again.

On Fri, Feb 20, 2015 at 10:17 PM, Kelli Johnson notifications@github.com
wrote:

> Closed #18 https://github.com/ss3sim/ss3models/issues/18.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ss3sim/ss3models/issues/18#event-239559299.

## 

Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/
