### ISSUE TITLE
Hake and hake-age not consistent

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3models#20]
I tweaked the hake EM ctl file to improve convergence per Ian's suggestion with commit https://github.com/ss3sim/ss3models/commit/5b8d6e77cb9ed786d4fa17e5de4835fd652cc3bd. When I went to make the same change to hake-age I noticed the settings for lnR0 are different. The bounds for hake are 4-20 while for hake-age they are 13-17.

I was under the impression that the models were standardized and the only differences with the age selex versions was the maturity and selex params. Am I missing something? Is there more work to do?

**Comment by kellijohnson-NOAA** [comment]
The age models were not standardized b/c they were not finalized when
Christine ran the standardization code.

On Mon, Feb 23, 2015 at 4:51 PM, Cole Monnahan notifications@github.com
wrote:

> I tweaked the hake EM ctl file to improve convergence per Ian's suggestion
> with commit 5b8d6e7
> https://github.com/ss3sim/ss3models/commit/5b8d6e77cb9ed786d4fa17e5de4835fd652cc3bd.
> When I went to make the same change to hake-age I noticed the settings for
> lnR0 are different. The bounds for hake are 4-20 while for hake-age they
> are 13-17.
> 
> I was under the impression that the models were standardized and the only
> differences with the age selex versions was the maturity and selex params.
> Am I missing something? Is there more work to do?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ss3sim/ss3models/issues/20.

## 

Kelli Faye Johnson
kellifayejohnson@gmail.com

**Comment by colemonnahan** [comment]
Ahh, @cstawitz would you mind running your function for the -age models then? Kot says they're all ready to go. Thanks!

**Comment by cstawitz** [comment]
Done. I only did the -age ones, not the camel cased ones.

On Mon, Feb 23, 2015 at 5:20 PM, Cole Monnahan notifications@github.com
wrote:

> Ahh, @cstawitz https://github.com/cstawitz would you mind running your
> function for the -age models then? Kot says they're all ready to go. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ss3sim/ss3models/issues/20#issuecomment-75680513.

## 

Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Comment by peterkuriyama** [comment]
@colemonnahan I can use the F0-hake case files for hake-age right?

**Comment by colemonnahan** [comment]
@peterkuriyama the function I ran should have created F cases for hake-age. Do you not see them? They're slightly different for selex or maturity reasons presumably. If you don't see them I'll rerun and update.

**Comment by colemonnahan** [comment]
I matched the ctl settings so they're the same for now except the hake ctl doesn't seem to have all the ss_new formatting.

@cstawitz Thanks by the way!

**Comment by cstawitz** [comment]
By the way, there is an R script to standardize the bounds in the ss3models
repository in the "extra" folder (run_standardize_bounds.R). You just have
to change the indices on line 19 to reference the models you want to
standardize and optionally the parameter line numbers to standardize on
line 38.

I'm happy to do it whenever people ask, but just in case anyone is working
at crazy hours and doesn't want to wait for me to get to it.

On Mon, Feb 23, 2015 at 7:53 PM, Cole Monnahan notifications@github.com
wrote:

> I matched the ctl settings so they're the same for now except the hake ctl
> doesn't seem to have all the ss_new formatting.
> 
> @cstawitz https://github.com/cstawitz Thanks by the way!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ss3sim/ss3models/issues/20#issuecomment-75695301.

## 

Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/
