### ISSUE TITLE
mackerel-age not working (or matching mackerel)

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3models#21]
I'm getting dat file errors when trying to run mackerel-age. Looking at the .dat file I see what appears to me to be issues. The one row of comp data is for year 1938. Also the number of age bins differs (8 vs 12). The mackerel .dat file has the expected values at the bottom -- is that OK?

@Kotkot or @juanlvalero is this something you could look into please? I'll skip this model for now.

**Comment by juanlvalero** [comment]
I am closing this issue, the problems were fixed
