### ISSUE TITLE
SigmaR different between .ctl and .par files

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3models#23]
Unless I'm missing something, for cod the .par file has a sigmaR of 0.4, while the .ctl has it as 0.8. I believe `ss3sim` will grab the value from the ctl file and use that to generate the recdevs. Can someone verify this? Is this an issue and should we fix it?

**Comment by Kotkot** [comment]
I see 0.4 in the ctl file
 0    2    0.4    0.8    -1    0.8    -5 # SR_sigmaR

You are talking about the cod.ctl in ss3models/inst/models/cod/om/ss3.ctl ?

**Comment by kellijohnson-NOAA** [comment]
I also see the same line in the ss3sim/ss3sim/inst/extra/models/cod-om 
folder. I am guessing the 0 2 was read as a single number?

**Comment by colemonnahan** [comment]
Oh wow sorry, I think I've been looking at the screen too much. I was making a table and had a minor panic. Looks like we're good!
