### ISSUE TITLE
Working directory error in `get_parvalues`

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3models#25]
If this function fails it will leave the user in a temporary folder. A quick look at the code and it looks like the `on.exit` call to reset the path is overwritten later. I think this should be as easy as just stacking the `on.exit` calls...

Edit: Turns out if you have loose files in the `modelfolder` folder it tries to run those, throws an error (obviously), and leaves you in the temp directory.

Should just look at folders (not files) and test for whether there's an OM and EM directory.

**Comment by kellijohnson-NOAA** [comment]
Fixed with b1c51af116968403511849c41f0d8265b086e321. Also stacked `on.exit` calls with `add = TRUE`.
