### ISSUE TITLE
Model descriptions

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3models#3]
Can someone describe what cos is? I am unsure if I should be using that model instead of col and if col should be scrapped?
-KFJ

**Comment by colemonnahan** [comment]
Hi Kelli, we took col and changed the EM selectivity to double normal that mimics logistic. I wouldn't use it for any runs for the workshop, it shouldn't be that different and you want all your life history runs to be the same model.

**Comment by juanlvalero** [comment]
I second what Cole said. I wouldn't worry about updating our OM to the COS
for workshop runs, the logistic and double normal asymptotic should be very
similar anyways.
Juan

**Comment by kellijohnson-NOAA** [comment]
cos is now documented in the readme file and everyone should work on updating descriptions of all models placed in this repository
