### ISSUE TITLE
Species names don't need to be 3 characters

### ISSUE THREAD

**Issue by seananderson** [ss3sim/ss3models#5]
Just pointing this out. All that matters is they are lowercase and contain alphabetical characters only. No need to find a dozen ways to spell cod with 3 letters. ;)

If people don't object, maybe we can rename the models something more meaningful before people start using them extensively?

Maybe we could also include a README.md file in each model setup folder that gives a brief description? That will render when someone clicks on the folder on GitHub. Again just something to work towards.

**Comment by colemonnahan** [comment]
This is a great idea. I honestly thought we still had the 3 character restriction. I fully support more informative names and a README for each model would be great. @Kotkot has been keeping the growth_model repo organized so far. Perhaps he can get us started on that and delegate to some others.
