### ISSUE TITLE
cod-om

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3models#6]
In its current state the cod-om is not working, i.e., when I copy the files and run ss3 via the command window, ss_new files are not generated. Warnings are not helpful at a first glance. It points possibly to issues surrounding F.

**Comment by colemonnahan** [comment]
I'm also have the same issue. I asked @juanlvalero to take a look and see what's going on. The model files haven't been updated for 3 months so something must have changed inside the package.

**Comment by kellijohnson-NOAA** [comment]
Fixed with commit 6c6418f0f6ce0678aa17ebdcd63e226a3f7725df

**Comment by kellijohnson-NOAA** [comment]
If `ss3` is ran with `-nohess` one runs the risk of `ss_new` files being produced even if the model does not work. When testing be aware of this and even though models may take longer to run when you are testing code it may be worth it to run `ss3` in estimation mode even for the OM.
